//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionInfo.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SessionInfo.Res.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active console session:.
        /// </summary>
        internal static string ActiveConsoleSession {
            get {
                return ResourceManager.GetString("ActiveConsoleSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name: {0}.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Build Number: {0}.
        /// </summary>
        internal static string ClientBuildNumber {
            get {
                return ResourceManager.GetString("ClientBuildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Directory: {0}.
        /// </summary>
        internal static string ClientDirectory {
            get {
                return ResourceManager.GetString("ClientDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Display: {0}x{1} with {2} bits per pixel.
        /// </summary>
        internal static string ClientDisplay {
            get {
                return ResourceManager.GetString("ClientDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Hardware ID: {0}.
        /// </summary>
        internal static string ClientHardwareID {
            get {
                return ResourceManager.GetString("ClientHardwareID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Product ID: {0}.
        /// </summary>
        internal static string ClientProductID {
            get {
                return ResourceManager.GetString("ClientProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Protocol Type: {0}.
        /// </summary>
        internal static string ClientProtocolType {
            get {
                return ResourceManager.GetString("ClientProtocolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Time: {0}.
        /// </summary>
        internal static string ConnectTime {
            get {
                return ResourceManager.GetString("ConnectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current session:.
        /// </summary>
        internal static string CurrenSession {
            get {
                return ResourceManager.GetString("CurrenSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Time: {0}.
        /// </summary>
        internal static string IdleTime {
            get {
                return ResourceManager.GetString("IdleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming protocol statistics: .
        /// </summary>
        internal static string IncomingProtocolStatistics {
            get {
                return ResourceManager.GetString("IncomingProtocolStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Program: {0}.
        /// </summary>
        internal static string InitialProgram {
            get {
                return ResourceManager.GetString("InitialProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Working Directory: {0}.
        /// </summary>
        internal static string InitialWorkingDirectory {
            get {
                return ResourceManager.GetString("InitialWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address: {0}.
        /// </summary>
        internal static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Input Time: {0}.
        /// </summary>
        internal static string LastInputTime {
            get {
                return ResourceManager.GetString("LastInputTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon Time: {0}.
        /// </summary>
        internal static string LogonTime {
            get {
                return ResourceManager.GetString("LogonTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing protocol statistics: .
        /// </summary>
        internal static string OutgoingProtocolStatistics {
            get {
                return ResourceManager.GetString("OutgoingProtocolStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process ID: {0}.
        /// </summary>
        internal static string ProcessID {
            get {
                return ResourceManager.GetString("ProcessID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name: {0}.
        /// </summary>
        internal static string ProcessName {
            get {
                return ResourceManager.GetString("ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes: {0} Frames: {1} Compressed: {2}.
        /// </summary>
        internal static string ProtocolStatistics {
            get {
                return ResourceManager.GetString("ProtocolStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote endpoint: {0}.
        /// </summary>
        internal static string RemoteEndpoint {
            get {
                return ResourceManager.GetString("RemoteEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response: {0}.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session ID: {0}.
        /// </summary>
        internal static string SessionID {
            get {
                return ResourceManager.GetString("SessionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SID: {0}.
        /// </summary>
        internal static string SID {
            get {
                return ResourceManager.GetString("SID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State: {0}.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command: {0}.
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: SessionInfo ask [server] [session id] [icon] [caption] [text] [timeout] [buttons].
        /// </summary>
        internal static string UsageAsk {
            get {
                return ResourceManager.GetString("UsageAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: SessionInfo connect [source session id] [target session id] [password].
        /// </summary>
        internal static string UsageConnect {
            get {
                return ResourceManager.GetString("UsageConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: SessionInfo disconnect [server] [session id].
        /// </summary>
        internal static string UsageDisconnect {
            get {
                return ResourceManager.GetString("UsageDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: SessionInfo get [server] [session id].
        /// </summary>
        internal static string UsageGet {
            get {
                return ResourceManager.GetString("UsageGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: SessionInfo killprocess [server] [process id] [exit code].
        /// </summary>
        internal static string UsageKillProcess {
            get {
                return ResourceManager.GetString("UsageKillProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: SessionInfo listprocesses [server].
        /// </summary>
        internal static string UsageListProcesses {
            get {
                return ResourceManager.GetString("UsageListProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: SessionInfo listsessionprocesses [server] [session id].
        /// </summary>
        internal static string UsageListSessionProcesses {
            get {
                return ResourceManager.GetString("UsageListSessionProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: SessionInfo listsessions [server].
        /// </summary>
        internal static string UsageListSessions {
            get {
                return ResourceManager.GetString("UsageListSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: SessionInfo logoff [server] [session id].
        /// </summary>
        internal static string UsageLogoff {
            get {
                return ResourceManager.GetString("UsageLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: SessionInfo message [server] [session id] [icon] [caption] [text].
        /// </summary>
        internal static string UsageMessage {
            get {
                return ResourceManager.GetString("UsageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: SessionInfo shutdown [server] [shutdown type].
        /// </summary>
        internal static string UsageShutdown {
            get {
                return ResourceManager.GetString("UsageShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: SessionInfo startremotecontrol [server] [session id] [modifier] [hotkey].
        /// </summary>
        internal static string UsageStartRemoteControl {
            get {
                return ResourceManager.GetString("UsageStartRemoteControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: SessionInfo stopremotecontrol [session id].
        /// </summary>
        internal static string UsageStopRemoteControl {
            get {
                return ResourceManager.GetString("UsageStopRemoteControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: {0}.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for events; press Enter to exit..
        /// </summary>
        internal static string WaitEnterExitMsg {
            get {
                return ResourceManager.GetString("WaitEnterExitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Station: {0}.
        /// </summary>
        internal static string WindowStation {
            get {
                return ResourceManager.GetString("WindowStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Set: {0}.
        /// </summary>
        internal static string WorkingSet {
            get {
                return ResourceManager.GetString("WorkingSet", resourceCulture);
            }
        }
    }
}
